sonar.projectKey=backend
sonar.working.directory=C:\\Users\\sienk\\Desktop\\SystemEwidencjiSzkolnej\\backend\\backend\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=C:\\Users\\sienk\\Desktop\\SystemEwidencjiSzkolnej\\backend\\backend
sonar.pullrequest.cache.basepath=C:\\Users\\sienk\\Desktop\\SystemEwidencjiSzkolnej\\backend\\backend

0BDCCEFC-3672-48CE-B174-1314BA6EF854.sonar.projectKey=backend:0BDCCEFC-3672-48CE-B174-1314BA6EF854
0BDCCEFC-3672-48CE-B174-1314BA6EF854.sonar.projectName=backend
0BDCCEFC-3672-48CE-B174-1314BA6EF854.sonar.projectBaseDir=C:\\Users\\sienk\\Desktop\\SystemEwidencjiSzkolnej\\backend\\backend
0BDCCEFC-3672-48CE-B174-1314BA6EF854.sonar.sourceEncoding=utf-8
0BDCCEFC-3672-48CE-B174-1314BA6EF854.sonar.tests=
0BDCCEFC-3672-48CE-B174-1314BA6EF854.sonar.sources=\
"C:\\Users\\sienk\\Desktop\\SystemEwidencjiSzkolnej\\backend\\backend\\Controllers\\AuthController.cs",\
"C:\\Users\\sienk\\Desktop\\SystemEwidencjiSzkolnej\\backend\\backend\\Controllers\\ClassroomController.cs",\
"C:\\Users\\sienk\\Desktop\\SystemEwidencjiSzkolnej\\backend\\backend\\Controllers\\ClassroomEquipmentController.cs",\
"C:\\Users\\sienk\\Desktop\\SystemEwidencjiSzkolnej\\backend\\backend\\Controllers\\EquipmentReadController.cs",\
"C:\\Users\\sienk\\Desktop\\SystemEwidencjiSzkolnej\\backend\\backend\\Controllers\\EquipmentWriteController.cs",\
"C:\\Users\\sienk\\Desktop\\SystemEwidencjiSzkolnej\\backend\\backend\\Controllers\\LocationController.cs",\
"C:\\Users\\sienk\\Desktop\\SystemEwidencjiSzkolnej\\backend\\backend\\Controllers\\RegisterController.cs",\
"C:\\Users\\sienk\\Desktop\\SystemEwidencjiSzkolnej\\backend\\backend\\Controllers\\RolesController.cs",\
"C:\\Users\\sienk\\Desktop\\SystemEwidencjiSzkolnej\\backend\\backend\\Controllers\\UpdateRolaRequest.cs",\
"C:\\Users\\sienk\\Desktop\\SystemEwidencjiSzkolnej\\backend\\backend\\Controllers\\UsersController.cs",\
"C:\\Users\\sienk\\Desktop\\SystemEwidencjiSzkolnej\\backend\\backend\\Data\\AppDbContext.cs",\
"C:\\Users\\sienk\\Desktop\\SystemEwidencjiSzkolnej\\backend\\backend\\Models\\AddClassroomRequest.cs",\
"C:\\Users\\sienk\\Desktop\\SystemEwidencjiSzkolnej\\backend\\backend\\Models\\AddEquipmentRequest.cs",\
"C:\\Users\\sienk\\Desktop\\SystemEwidencjiSzkolnej\\backend\\backend\\Models\\Classroom.cs",\
"C:\\Users\\sienk\\Desktop\\SystemEwidencjiSzkolnej\\backend\\backend\\Models\\Equipment.cs",\
"C:\\Users\\sienk\\Desktop\\SystemEwidencjiSzkolnej\\backend\\backend\\Models\\EquipmentHistory.cs",\
"C:\\Users\\sienk\\Desktop\\SystemEwidencjiSzkolnej\\backend\\backend\\Models\\Location.cs",\
"C:\\Users\\sienk\\Desktop\\SystemEwidencjiSzkolnej\\backend\\backend\\Models\\LoginRequest.cs",\
"C:\\Users\\sienk\\Desktop\\SystemEwidencjiSzkolnej\\backend\\backend\\Models\\RegisterRequest.cs",\
"C:\\Users\\sienk\\Desktop\\SystemEwidencjiSzkolnej\\backend\\backend\\Models\\Role.cs",\
"C:\\Users\\sienk\\Desktop\\SystemEwidencjiSzkolnej\\backend\\backend\\Models\\UpdateEquipmentRequest.cs",\
"C:\\Users\\sienk\\Desktop\\SystemEwidencjiSzkolnej\\backend\\backend\\Models\\User.cs",\
"C:\\Users\\sienk\\Desktop\\SystemEwidencjiSzkolnej\\backend\\backend\\Program.cs",\
"C:\\Users\\sienk\\Desktop\\SystemEwidencjiSzkolnej\\backend\\backend\\obj\\Debug\\net8.0\\backend.GlobalUsings.g.cs",\
"C:\\Users\\sienk\\Desktop\\SystemEwidencjiSzkolnej\\backend\\backend\\obj\\Debug\\net8.0\\.NETCoreApp,Version=v8.0.AssemblyAttributes.cs",\
"C:\\Users\\sienk\\Desktop\\SystemEwidencjiSzkolnej\\backend\\backend\\obj\\Debug\\net8.0\\backend.AssemblyInfo.cs",\
"C:\\Users\\sienk\\Desktop\\SystemEwidencjiSzkolnej\\backend\\backend\\obj\\Debug\\net8.0\\backend.MvcApplicationPartsAssemblyInfo.cs",\
"C:\\Users\\sienk\\Desktop\\SystemEwidencjiSzkolnej\\backend\\backend\\appsettings.Development.json",\
"C:\\Users\\sienk\\Desktop\\SystemEwidencjiSzkolnej\\backend\\backend\\appsettings.json",\
"C:\\Users\\sienk\\Desktop\\SystemEwidencjiSzkolnej\\backend\\backend\\backend.http",\
"C:\\Users\\sienk\\Desktop\\SystemEwidencjiSzkolnej\\backend\\backend\\Dockerfile",\
"C:\\Users\\sienk\\Desktop\\SystemEwidencjiSzkolnej\\backend\\backend\\Properties\\launchSettings.json",\
"C:\\Users\\sienk\\Desktop\\SystemEwidencjiSzkolnej\\backend\\backend\\obj\\backend.csproj.nuget.dgspec.json",\
"C:\\Users\\sienk\\Desktop\\SystemEwidencjiSzkolnej\\backend\\backend\\obj\\project.assets.json",\
"C:\\Users\\sienk\\Desktop\\SystemEwidencjiSzkolnej\\backend\\backend\\bin\\Debug\\net8.0\\appsettings.Development.json",\
"C:\\Users\\sienk\\Desktop\\SystemEwidencjiSzkolnej\\backend\\backend\\bin\\Debug\\net8.0\\appsettings.json",\
"C:\\Users\\sienk\\Desktop\\SystemEwidencjiSzkolnej\\backend\\backend\\bin\\Debug\\net8.0\\backend.deps.json",\
"C:\\Users\\sienk\\Desktop\\SystemEwidencjiSzkolnej\\backend\\backend\\bin\\Debug\\net8.0\\backend.runtimeconfig.json",\
"C:\\Users\\sienk\\Desktop\\SystemEwidencjiSzkolnej\\backend\\backend\\bin\\Debug\\net8.0\\backend.staticwebassets.endpoints.json",\
"C:\\Users\\sienk\\Desktop\\SystemEwidencjiSzkolnej\\backend\\backend\\obj\\Debug\\net8.0\\backend.sourcelink.json",\
"C:\\Users\\sienk\\Desktop\\SystemEwidencjiSzkolnej\\backend\\backend\\obj\\Debug\\net8.0\\rjsmcshtml.dswa.cache.json",\
"C:\\Users\\sienk\\Desktop\\SystemEwidencjiSzkolnej\\backend\\backend\\obj\\Debug\\net8.0\\rjsmrazor.dswa.cache.json",\
"C:\\Users\\sienk\\Desktop\\SystemEwidencjiSzkolnej\\backend\\backend\\obj\\Debug\\net8.0\\rpswa.dswa.cache.json",\
"C:\\Users\\sienk\\Desktop\\SystemEwidencjiSzkolnej\\backend\\backend\\obj\\Debug\\net8.0\\staticwebassets.build.endpoints.json",\
"C:\\Users\\sienk\\Desktop\\SystemEwidencjiSzkolnej\\backend\\backend\\obj\\Debug\\net8.0\\staticwebassets.build.json"

0BDCCEFC-3672-48CE-B174-1314BA6EF854.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\sienk\\Desktop\\SystemEwidencjiSzkolnej\\backend\\backend\\.sonarqube\\out\\0"
0BDCCEFC-3672-48CE-B174-1314BA6EF854.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\sienk\\Desktop\\SystemEwidencjiSzkolnej\\backend\\backend\\.sonarqube\\out\\0\\Issues.json"
0BDCCEFC-3672-48CE-B174-1314BA6EF854.sonar.cs.scanner.telemetry=\
"C:\\Users\\sienk\\Desktop\\SystemEwidencjiSzkolnej\\backend\\backend\\.sonarqube\\out\\0\\Telemetry.json"

0BDCCEFC-3672-48CE-B174-1314BA6EF854.sonar.working.directory=C:\\Users\\sienk\\Desktop\\SystemEwidencjiSzkolnej\\backend\\backend\\.sonarqube\\out\\.sonar\\mod0
sonar.host.url=http://localhost:9000
sonar.visualstudio.enable=false

sonar.modules=0BDCCEFC-3672-48CE-B174-1314BA6EF854

